### PR TITLE
+ psi-omemo stub

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by msva** [comment]
not sure if this is a bug of ebuild or plugin:
```gcc
git symbolic-ref refs/git-r3/net-im/psi-omemo/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/psi-im/plugins.git to /var/tmp/portage/net-im/psi-omemo-9999/work/plugins ...
git checkout --quiet refs/git-r3/HEAD
GIT NEW branch -->
   repository:               https://github.com/psi-im/plugins.git
   at the commit:            341621cecf36ef81fa2255763a4ba50ba817a2a4
 * Running qmake ...
Info: creating stash file /var/tmp/portage/net-im/psi-omemo-9999/work/plugins/dev/omemoplugin/.qmake.stash
Cannot read /var/tmp/portage/net-im/psi-omemo-9999/conf.pri: No such file or directory
 [ ok ]
In file included from src/signal.cpp:22:0:
src/crypto.h:40:35: error: ‘AuthTag’ is not a member of ‘QCA’
     static QPair<QByteArray, QCA::AuthTag>
                                   ^~~~~~~
src/crypto.h:40:35: error: ‘AuthTag’ is not a member of ‘QCA’
src/crypto.h:40:42: error: template argument 2 is invalid
     static QPair<QByteArray, QCA::AuthTag>
                                          ^
src/crypto.h:45:24: error: ‘AuthTag’ in namespace ‘QCA’ does not name a type
             const QCA::AuthTag &tag = QCA::AuthTag(OMEMO_AES_GCM_TAG_LENGTH));
                        ^~~~~~~
src/crypto.h:45:44: error: ‘AuthTag’ is not a member of ‘QCA’
             const QCA::AuthTag &tag = QCA::AuthTag(OMEMO_AES_GCM_TAG_LENGTH));
                                            ^~~~~~~
src/signal.cpp: In member function ‘void psiomemo::Signal::processBundle(const QString&, uint32_t, const psiomemo::Bundle&)’:
src/signal.cpp:132:60: error: ‘QRandomGenerator’ has not been declared
     QPair<uint32_t, QByteArray> preKey = bundle.preKeys.at(QRandomGenerator::global()->bounded(bundle.preKeys.size()));
                                                            ^~~~~~~~~~~~~~~~
make: *** [Makefile:1162: .obj/signal.o] Error 1
 * ERROR: net-im/psi-omemo-9999::rion failed (compile phase):
```

**Comment by Ri0n** [comment]
most likely ebuild's bug. it should require newer qca

**Comment by Ri0n** [comment]
I already noticed this in chat. bad plugin's project file

**Comment by msva** [comment]
by the way, even with new qca:
```
src/signal.cpp: In member function ‘void psiomemo::Signal::processBundle(const QString&, uint32_t, const psiomemo::Bundle&)’:
src/signal.cpp:132:60: error: ‘QRandomGenerator’ has not been declared
     QPair<uint32_t, QByteArray> preKey = bundle.preKeys.at(QRandomGenerator::global()->bounded(bundle.preKeys.size()));
                                                            ^~~~~~~~~~~~~~~~
make: *** [Makefile:1162: .obj/signal.o] Error 1
make: *** Waiting for unfinished jobs....
src/storage.cpp: In member function ‘void psiomemo::Storage::init(signal_context*, const QString&)’:
src/storage.cpp:42:30: error: invalid conversion from ‘int (*)(signal_buffer**, const signal_protocol_address*, void*)’ to ‘int (*)(signal_buffer**, signal_buffer**, const signal_protocol_address*, void*)’ [-fpermissive]
         .load_session_func = &loadSession,
                              ^~~~~~~~~~~~
src/storage.cpp:44:31: error: invalid conversion from ‘int (*)(const signal_protocol_address*, uint8_t*, size_t, void*) {aka int (*)(const signal_protocol_address*, unsigned char*, long unsigned int, void*)}’ to ‘int (*)(const signal_protocol_address*, uint8_t*, size_t, uint8_t*, size_t, void*) {aka int (*)(const signal_protocol_address*, unsigned char*, long unsigned int, unsigned char*, long unsigned int, void*)}’ [-fpermissive]
         .store_session_func = &storeSession,
                               ^~~~~~~~~~~~~
make: *** [Makefile:1165: .obj/storage.o] Error 1
```

// and libsignal-c is definitely installed and definitely 9999

**Comment by msva** [comment]
looks like:
1) it requires qt-5.10 (`QRandomGenerator`), and not added to deps (as well as qca-9999)
2) libsignal-protocol-c changed it's API since the plugin was merged (`invalid conversion`), so, it (signal lib ebuild) probably need some snapshot instead of 9999 version :-/

**Comment by Vitozz** [comment]
This plugin requires libsignal-protocol-c-2.3.1 only

**Comment by msva** [comment]
Well, @Vitozz, `QRandomGenerator` appeared only in Qt-5.10.
And talking on `invalid conversion`, by the way, clang compiles this code fine (while gcc-7.3 is not), so, it can be fixed with proper CXXFLAGS settings, I guess.

**Comment by msva** [comment]
Well, after @Ri0n 's changes to the plugin code - any next readers of this thread should nevermind all of that ;)

**Comment by Ri0n** [comment]
now it may compile with any version of libsignal-protocol-c

**Pull request merged**
